-----------------------------------------------------------------
-- Скрипт создания прав пользователя 
-----------------------------------------------------------------


DEFINE GRANTEE = '&&USERNAME.'
DEFINE SCRIPT_MSG = 'Cкрипт выдачи полномочий пользователю &&GRANTEE.'

SET SERVEROUTPUT ON SIZE UNLIMITED
SET HEADING OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SET VERIFY OFF
SET TRIMOUT ON
SET TRIMSPOOL ON
SET AUTOPRINT OFF
SET SHOWMODE ON
SET TIME ON
SET PAGESIZE 0 LINESIZE 2000 LONGCHUNKSIZE 2000 LONG 1000000

SPOOL _02.2_grant_user.log

PROMPT &&SCRIPT_MSG. запущен


GRANT CONNECT TO &&GRANTEE.
/
GRANT RESOURCE TO &&GRANTEE.
/
ALTER USER &&GRANTEE. DEFAULT ROLE ALL
/
GRANT ALTER SESSION TO &&GRANTEE.
/
GRANT UNLIMITED TABLESPACE TO &&GRANTEE.
/
GRANT CREATE TABLE TO &&GRANTEE.
/
GRANT CREATE VIEW TO &&GRANTEE.
/
GRANT CREATE PROCEDURE TO &&GRANTEE.
/
GRANT CREATE SEQUENCE TO &&GRANTEE.
/
GRANT CREATE TRIGGER TO &&GRANTEE.
/
GRANT CREATE DATABASE LINK TO &&GRANTEE.
/
GRANT EXECUTE ON SYS.DBMS_LOCK TO &&GRANTEE.
/


-- создание и поддержка JOB, CHAIN, SCHEDULE для очистки устаревших данных
GRANT CREATE JOB TO &&GRANTEE.
/
GRANT MANAGE SCHEDULER TO &&GRANTEE.
/
GRANT CREATE EVALUATION CONTEXT TO &&GRANTEE.
/
GRANT CREATE RULE TO &&GRANTEE.
/
GRANT CREATE RULE SET TO &&GRANTEE.
/

--пришло от заказчика и нужно для работы с внешними таблицами
--GRANT READ ON DIRECTORY inf TO &&GRANTEE.
--/
--GRANT WRITE ON DIRECTORY inf TO &&GRANTEE.
--/

PROMPT &&SCRIPT_MSG. выполнен
SPOOL OFF

UNDEF GRANTEE
UNDEF SCRIPT_MSG